services:
  - type: web
    name: iniesta-smdl-pro
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
    # This auto-restarts if the server crashes
    autoDeploy: true
