services:
  - type: web
    name: iniesta-downloader-api
    runtime: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    healthCheckPath: /health
